name = "spydon"
license = "Apache License 2.0"
licenselink = "//github.com/digitalcraftsman/hugo-freelancer-theme/blob/master/LICENSE"
description = "A one page HTML theme for day 10 000."
homepage = "//github.com/spydon/nibbe-club"
tags = ["birthday", "10000"]
features = ["responsive", "substitutable strings"]
min_version = 0.14

[author]
  name = "spydon"
  homepage = "//github.com/spydon"

# If porting an existing theme
[[author]]
  name = "digitalcraftsman"
  homepage = "//github.com/digitalcraftsman"

[[original]]
  # Creator of the original Bootstrap theme
  name = "David Miller"
  homepage = "//www.ironsummitmedia.com/"
  repo = "//github.com/IronSummitMedia/startbootstrap-freelancer"

[[original]]
  # Creator of the ported Jekyll theme
  name = "Jerome Lachaud"
  homepage = "//jeromelachaud.com/"
  repo = "//github.com/jeromelachaud/freelancer-theme"
